"""
Type definitions for the knowledge distillation pipeline.

Contains dataclasses for:
- KnowledgeEntry, ProjectEntry (output types)
- NormalizedConversation (intermediate format)
- ThinIndex (compressed index for retrieval)
"""

from .entries import (
    Evidence,
    Insight,
    Capability,
    OpenQuestion,
    RepoLink,
    Position,
    Evolution,
    KnowledgeMetadata,
    KnowledgeEntry,
    Decision,
    ProjectMetadata,
    ProjectEntry,
)
from .normalized import (
    CodeBlock,
    NormalizedMessage,
    ParseMetadata,
    NormalizedConversation,
)
from .thin_index import (
    ThinIndexTopic,
    ThinIndexProject,
    ThinIndexEvolution,
    ThinIndex,
)
from .phase7 import (
    AUTHORITY_RANK,
    PHASE7_SCHEMA_VERSION,
    Phase7CompiledClaim,
    Phase7MigrationPreview,
    Phase7Observation,
    Phase7SupersessionEdge,
    compiled_claims_from_observations,
    highest_source_authority,
    normalize_claim_text,
    observations_from_legacy_entry,
    preview_phase7_migration,
    provisional_claim_from_observation,
    retrieval_projection_from_claims,
    stable_phase7_id,
)
from .phase7b import (
    Phase7EntityIndexEntry,
    Phase7EntityMention,
    Phase7TemporalResolution,
    build_entity_index,
    enrich_claim_temporal,
    enrich_claims_phase7b,
    enrich_observation_temporal,
    enrich_observations_phase7b,
    evaluate_phase7b_temporal_probe,
    extract_entity_mentions,
    normalize_entity_name,
    normalize_temporal_text,
    stable_entity_id,
)
from .phase7c import (
    PHASE7C_SCHEMA_VERSION,
    Phase7CompileGrade,
    Phase7CompileGradeIssue,
    Phase7CompileProposalOperation,
    Phase7CurrentView,
    Phase7ProjectionExcludedClaim,
    build_compile_claim_operation,
    build_compile_claim_operations_from_observations,
    build_mark_current_operation,
    build_supersede_claim_operation,
    generate_compiled_current_view,
    grade_phase7c_compile_operations,
)
from .phase7d import (
    PHASE7D_SCHEMA_VERSION,
    Phase7MemoryBlock,
    build_operator_profile_block,
    build_phase7d_memory_blocks,
    build_policy_pointer_block,
    build_project_status_block,
    stable_memory_block_id,
)
from .phase7_acceptance import (
    PHASE7_ACCEPTANCE_SCHEMA_VERSION,
    Phase7AcceptanceCheck,
    Phase7AcceptanceReport,
    run_phase7_acceptance,
    run_phase7_acceptance_fixture,
)
from .phase8 import (
    PHASE8_SCHEMA_VERSION,
    Phase8EvalCheck,
    Phase8EvalReport,
    Phase8QueryIntent,
    Phase8RetrievalCandidate,
    Phase8RetrievalReport,
    Phase8RetrievalResult,
    build_phase8_candidates,
    classify_phase8_query,
    evaluate_phase8_retrieval_probes,
    retrieve_phase8,
    run_phase8_retrieval_fixture,
)

__all__ = [
    # Entry types
    "Evidence",
    "Insight",
    "Capability",
    "OpenQuestion",
    "RepoLink",
    "Position",
    "Evolution",
    "KnowledgeMetadata",
    "KnowledgeEntry",
    "Decision",
    "ProjectMetadata",
    "ProjectEntry",
    # Normalized conversation types
    "CodeBlock",
    "NormalizedMessage",
    "ParseMetadata",
    "NormalizedConversation",
    # Index types
    "ThinIndexTopic",
    "ThinIndexProject",
    "ThinIndexEvolution",
    "ThinIndex",
    # Phase 7A schema
    "AUTHORITY_RANK",
    "PHASE7_SCHEMA_VERSION",
    "Phase7CompiledClaim",
    "Phase7MigrationPreview",
    "Phase7Observation",
    "Phase7SupersessionEdge",
    "compiled_claims_from_observations",
    "highest_source_authority",
    "normalize_claim_text",
    "observations_from_legacy_entry",
    "preview_phase7_migration",
    "provisional_claim_from_observation",
    "retrieval_projection_from_claims",
    "stable_phase7_id",
    # Phase 7B enrichment
    "Phase7EntityIndexEntry",
    "Phase7EntityMention",
    "Phase7TemporalResolution",
    "build_entity_index",
    "enrich_claim_temporal",
    "enrich_claims_phase7b",
    "enrich_observation_temporal",
    "enrich_observations_phase7b",
    "evaluate_phase7b_temporal_probe",
    "extract_entity_mentions",
    "normalize_entity_name",
    "normalize_temporal_text",
    "stable_entity_id",
    # Phase 7C compiled current view
    "PHASE7C_SCHEMA_VERSION",
    "Phase7CompileGrade",
    "Phase7CompileGradeIssue",
    "Phase7CompileProposalOperation",
    "Phase7CurrentView",
    "Phase7ProjectionExcludedClaim",
    "build_compile_claim_operation",
    "build_compile_claim_operations_from_observations",
    "build_mark_current_operation",
    "build_supersede_claim_operation",
    "generate_compiled_current_view",
    "grade_phase7c_compile_operations",
    # Phase 7D memory blocks
    "PHASE7D_SCHEMA_VERSION",
    "Phase7MemoryBlock",
    "build_operator_profile_block",
    "build_phase7d_memory_blocks",
    "build_policy_pointer_block",
    "build_project_status_block",
    "stable_memory_block_id",
    # Phase 7 acceptance harness
    "PHASE7_ACCEPTANCE_SCHEMA_VERSION",
    "Phase7AcceptanceCheck",
    "Phase7AcceptanceReport",
    "run_phase7_acceptance",
    "run_phase7_acceptance_fixture",
    # Phase 8 offline retrieval
    "PHASE8_SCHEMA_VERSION",
    "Phase8EvalCheck",
    "Phase8EvalReport",
    "Phase8QueryIntent",
    "Phase8RetrievalCandidate",
    "Phase8RetrievalReport",
    "Phase8RetrievalResult",
    "build_phase8_candidates",
    "classify_phase8_query",
    "evaluate_phase8_retrieval_probes",
    "retrieve_phase8",
    "run_phase8_retrieval_fixture",
]
