#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ENV_PATH = REPO_ROOT / ".env.staging.local"


def auth_header(email: str, api_key: str) -> str:
    token = base64.b64encode(f"{email}:{api_key}".encode()).decode()
    return f"Basic {token}"


def api_request(
    method: str,
    path: str,
    *,
    email: str,
    api_key: str,
    body: dict[str, Any] | None = None,
) -> Any:
    data = json.dumps(body).encode() if body is not None else None
    request = urllib.request.Request(
        f"https://api.upstash.com/v2/{path.lstrip('/')}",
        data=data,
        method=method,
        headers={
            "Authorization": auth_header(email, api_key),
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            text = response.read().decode()
            return json.loads(text) if text else None
    except urllib.error.HTTPError as error:
        detail = error.read().decode(errors="replace")
        raise RuntimeError(f"Upstash API {method} {path} failed with HTTP {error.code}: {detail}") from error


def normalize_redis_rest_url(database: dict[str, Any]) -> str:
    endpoint = str(database.get("endpoint") or "")
    if not endpoint:
        raise RuntimeError("Created Redis database did not return an endpoint")
    if endpoint.startswith("http://") or endpoint.startswith("https://"):
        return endpoint
    host = endpoint if endpoint.endswith(".upstash.io") else f"{endpoint}.upstash.io"
    return f"https://{host}"


def normalize_vector_rest_url(index: dict[str, Any]) -> str:
    endpoint = str(index.get("endpoint") or "")
    if not endpoint:
        raise RuntimeError("Created Vector index did not return an endpoint")
    if endpoint.startswith("http://") or endpoint.startswith("https://"):
        return endpoint
    host = endpoint if endpoint.endswith(".upstash.io") else f"{endpoint}.upstash.io"
    return f"https://{host}"


def create_redis(email: str, api_key: str, name: str, region: str) -> dict[str, Any]:
    return api_request(
        "POST",
        "redis/database",
        email=email,
        api_key=api_key,
        body={
            "database_name": name,
            "name": name,
            "platform": "aws",
            "primary_region": region,
            "region": region,
            "plan": "payg",
            "tls": True,
            "eviction": False,
        },
    )


def create_vector(email: str, api_key: str, name: str, region: str, dimension_count: int) -> dict[str, Any]:
    return api_request(
        "POST",
        "vector/index",
        email=email,
        api_key=api_key,
        body={
            "name": name,
            "region": region,
            "similarity_function": "COSINE",
            "dimension_count": dimension_count,
            "type": "payg",
            "index_type": "DENSE",
        },
    )


def write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/provision_staging_upstash.py",
        "# This file contains secrets and is ignored by git.",
    ]
    for key, value in values.items():
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Provision isolated Upstash Redis/Vector resources for PKS staging.")
    parser.add_argument("--name-prefix", default=f"pks-v2-staging-{int(time.time())}")
    parser.add_argument("--redis-region", default="us-east-1")
    parser.add_argument("--vector-region", default="us-east-1")
    parser.add_argument("--dimension-count", type=int, default=3072)
    parser.add_argument("--env-path", type=Path, default=DEFAULT_ENV_PATH)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    email = os.getenv("UPSTASH_EMAIL", "")
    api_key = os.getenv("UPSTASH_API_KEY", "")
    if not email:
        raise RuntimeError("Missing UPSTASH_EMAIL")
    if not api_key:
        raise RuntimeError("Missing UPSTASH_API_KEY")

    redis_name = f"{args.name_prefix}-redis"
    vector_name = f"{args.name_prefix}-vector"
    if args.dry_run:
        print(f"Would create Redis database: {redis_name}")
        print(f"Would create Vector index: {vector_name}")
        print(f"Would write staging env file: {args.env_path}")
        return 0

    redis = create_redis(email, api_key, redis_name, args.redis_region)
    vector = create_vector(email, api_key, vector_name, args.vector_region, args.dimension_count)
    values = {
        "STAGING_UPSTASH_REDIS_REST_URL": normalize_redis_rest_url(redis),
        "STAGING_UPSTASH_REDIS_REST_TOKEN": str(redis.get("rest_token") or redis.get("token") or ""),
        "STAGING_UPSTASH_VECTOR_REST_URL": normalize_vector_rest_url(vector),
        "STAGING_UPSTASH_VECTOR_REST_TOKEN": str(vector.get("token") or ""),
        "STAGING_DREAM_OPERATOR_TOKEN": secrets.token_urlsafe(32),
        "STAGING_WORKER_BASE_URL": "https://arjun-knowledge-mcp-staging.arjun-divecha.workers.dev",
    }
    missing = [key for key, value in values.items() if not value]
    if missing:
        raise RuntimeError(f"Created resources but response lacked required fields: {', '.join(missing)}")
    write_env_file(args.env_path, values)
    print(f"Created staging Redis database: {redis_name}")
    print(f"Created staging Vector index: {vector_name}")
    print(f"Wrote staging env file: {args.env_path}")
    print("Load it with: set -a; source .env.staging.local; set +a")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:  # noqa: BLE001
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
